services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - broker
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: flask run --debug --host=0.0.0.0 --port=8080

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - db_app:/var/lib/postgresql/data/

  broker:
    image: redis:6
    ports:
      - 6379:6379
    healthcheck:
      interval: 20s
      retries: 3
      start_period: 10s
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
    volumes:
      - broker_app:/data
    

volumes:
  db_app:
  broker_app: