"""update subscribed column

Revision ID: e62b77a94586
Revises: 05d7c4fb90e1
Create Date: 2024-02-20 00:28:34.341464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e62b77a94586'
down_revision: Union[str, None] = '05d7c4fb90e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_recipients', sa.Column('subscribed', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'campaign_recipients', ['email_campaign_id'])
    op.drop_column('recipients', 'subscribed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipients', sa.Column('subscribed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'campaign_recipients', type_='unique')
    op.drop_column('campaign_recipients', 'subscribed')
    # ### end Alembic commands ###
